version: '3.8'

services:
  web:
    build: ./web
    image: web:custom
    container_name: web
    restart: unless-stopped
    command: flask run -h 0.0.0.0
    ports:
      - 5000:5000
  db:
    image: postgres:13-alpine
    container_name: postgres
    restart: unless-stopped
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_volume: 