version: '3.5'

services:
  web:
    image: mcodegeeks/web:latest
    container_name: web
    restart: unless-stopped
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - "54320:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  nginx:
    image: nginx:1.18-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_volume:
    external: false